[pytest]
minversion = 7.0
addopts = -p pytest_env --cov=flask/src --cov-report term-missing
pythonpath = flask/src
testpaths = flask/tests
env =
    DEBUG=False
    POD_NAME=test-pod
    AZURE_OPENAI_KEY=test-key
    AZURE_OPENAI_ENDPOINT=test-endpoint
    AZURE_OPENAI_DEPLOYMENT_NAME=test-deployment
    AZURE_AIFOUNDRY_PROJECT_ENDPOINT=test-project-endpoint
    ASSISTANT_ID=test-assistant-id
    FEEDBACK_SMTP_SERVER=test-smtp
    FEEDBACK_SMTP_PORT=25
    FEEDBACK_MAIL_RECIPIENT=test-recipient@example.com
    FEEDBACK_SMTP_SENDER_EMAIL=test-sender@example.com
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=mysecretpassword
    POSTGRES_HOST=localhost
    POSTGRES_PORT=5432
    POSTGRES_DB=ai_chat_db