[pytest]
minversion = 7.0
addopts = -p pytest_env --cov=flask/src --cov-report term-missing
pythonpath = flask/src
testpaths = flask/tests
env =
    DEBUG=False
    POD_NAME=test-pod
    AZURE_OPENAI_KEY=test-key
    AZURE_OPENAI_ENDPOINT=test-endpoint
    AZURE_OPENAI_DEPLOYMENT_NAME=test-deployment
    ASSISTANT_ID=test-assistant-id
    FEEDBACK_MAIL_API_URL=test-feedback-url
    FEEDBACK_MAIL_API_RECIPIENT=test-recipient@example.com
    FEEDBACK_MAIL_API_SENDER=test-sender@example.com
    POSTGRES_USER=postgres
    POSTGRES_PASSWORD=mysecretpassword
    POSTGRES_HOST=localhost
    POSTGRES_PORT=5432
    POSTGRES_DB=ai_chat_db